name: FlutterNews
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  url_launcher: ^4.0.2
  share: ^0.6.0+1
  http: ^0.12.0
  bsev: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
      - assets/place_holder.jpg
      - assets/place_holder_2.jpg
      - assets/place_holder_3.jpg
      - resources/lang/en.json
      - resources/lang/pt.json
